#!/bin/bash

echo "Setting up HW3 test environment..."

# Create public directory if it doesn't exist
mkdir -p public
mkdir -p public/cgi-bin

# Create required static test files
echo "Creating static test files..."

cat > public/pageA.txt << 'EOF'
This is page A content for testing the web server.
This file is used to test static GET requests.
It should be served by the web server and statistics should be collected.
EOF

cat > public/pageB.txt << 'EOF'  
This is page B content for testing the web server.
This file is used for both GET and POST request testing.
The server should handle multiple concurrent requests for this file.
EOF

cat > public/pageC.txt << 'EOF'
This is page C content for testing the web server.
This file tests the server's ability to handle different files.
Statistics should properly track requests for different files.
EOF

# Create a simple home page as mentioned in the assignment
cat > public/home.html << 'EOF'
<!DOCTYPE html>
<html>
<head>
    <title>HW3 Test Web Server</title>
</head>
<body>
    <h1>Welcome to HW3 Test Server</h1>
    <p>This is the home page for testing the multi-threaded web server.</p>
    <h2>Test Files:</h2>
    <ul>
        <li><a href="/pageA.txt">Page A (static content)</a></li>
        <li><a href="/pageB.txt">Page B (static content)</a></li>
        <li><a href="/pageC.txt">Page C (static content)</a></li>
        <li><a href="/cgi-bin/test.cgi">Test CGI (dynamic content)</a></li>
    </ul>
</body>
</html>
EOF

# Create CGI scripts for dynamic content testing
echo "Creating CGI test scripts..."

cat > public/cgi-bin/test.cgi << 'EOF'
#!/bin/bash
echo "Content-Type: text/html"
echo ""
echo "<html><head><title>CGI Test</title></head><body>"
echo "<h1>CGI Test Script</h1>"
echo "<p>This is dynamic content generated by a CGI script.</p>"
echo "<p>Current time: $(date)</p>"
echo "<p>Process ID: $$</p>"
echo "<p>This should increment the dynamic request counter.</p>"
echo "</body></html>"
EOF

# Create a CGI script that takes some time (for testing concurrent requests)
cat > public/cgi-bin/slow.cgi << 'EOF'
#!/bin/bash
echo "Content-Type: text/html"
echo ""
echo "<html><head><title>Slow CGI Test</title></head><body>"
echo "<h1>Slow CGI Script</h1>"
echo "<p>This script sleeps for 2 seconds to test concurrent handling...</p>"
sleep 2
echo "<p>Done sleeping! Current time: $(date)</p>"
echo "</body></html>"
EOF

# Create a parameterized CGI script
cat > public/cgi-bin/params.cgi << 'EOF'
#!/bin/bash
echo "Content-Type: text/html"
echo ""
echo "<html><head><title>CGI Parameters Test</title></head><body>"
echo "<h1>CGI Parameters Test</h1>"
echo "<p>Query String: $QUERY_STRING</p>"
echo "<p>This tests parameter passing to CGI scripts.</p>"
echo "</body></html>"
EOF

# Make CGI scripts executable
chmod +x public/cgi-bin/*.cgi

# Create some additional test files for stress testing
echo "Creating additional test files..."

cat > public/large.txt << 'EOF'
This is a larger file for testing the server's ability to handle bigger content.
EOF

# Add more content to make it larger
for i in {1..100}; do
    echo "Line $i: This is additional content to make the file larger for testing purposes." >> public/large.txt
done

# Create a small image file for testing different content types
echo "Creating test image..."
# Create a minimal valid GIF (1x1 transparent pixel)
printf '\x47\x49\x46\x38\x39\x61\x01\x00\x01\x00\x80\x00\x00\x00\x00\x00\xff\xff\xff\x21\xf9\x04\x01\x00\x00\x00\x00\x2c\x00\x00\x00\x00\x01\x00\x01\x00\x00\x02\x02\x04\x01\x00\x3b' > public/test.gif

# Create an HTML file that references other files
cat > public/index.html << 'EOF'
<!DOCTYPE html>
<html>
<head>
    <title>HW3 Test Index</title>
</head>
<body>
    <h1>HW3 Web Server Test Page